### ISSUE TITLE
testee hangs with chrome on travis

### ISSUE THREAD

**Issue by justinbmeyer** [bitovi/testee#103]
Here's my [travis configuration](https://github.com/canjs/can-ndjson-stream/blob/cc7318079ffcdc0f142aa651b0b96b680e737136/.travis.yml)

```yaml
sudo: false
dist: trusty
language: node_js
node_js: node
addons:
  apt:
    packages:
      - google-chrome-stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
- sleep 3
```

But the build never exits despite saying the single test has passed:

<img width="738" alt="cursor_and_build__22_-_canjs_can-ndjson-stream_-_travis_ci" src="https://cloud.githubusercontent.com/assets/78602/23334844/3db748d0-fb6d-11e6-8948-81d842a91e47.png">
